// leave off @2x/@3x
export default {
  logo: require('./images/logo/logo.png'),
  logoLoading: require('./images/logo/logoLoading.png'),
  logoCharcoal: require('./images/logo/logoCharcoal.png'),
  avatar: require('./images/avatar/avatar.png'),
  avatar2: require('./images/avatar/avatar2.png'),
  avatarBridge: require('./images/avatar/bridge.png'),
  introLogo: require('./images/avatar/intro-logo.png'),
  handshake: require('./images/google-sync/handshake.png'),
  iconGoogle: require('./images/google-sync/iconGoogle.png'),
  close: require('./images/google-sync/close.png'),
  logoNoText: require('./images/logo/logoNoText.png'),
  speedOfThought: require('./images/welcome/speedOfThought.png'),
  introFeedback: require('./images/welcome/introFeedback.png'),
  introTypes: require('./images/welcome/introTypes.png'),
  tabOverview: require('./images/tab/overview.png'),
  tabOverviewFilled: require('./images/tab/overview_filled.png'),
  tabNotifications: require('./images/tab/notifications.png'),
  tabNotificationsFilled: require('./images/tab/notifications_filled.png'),
  tabIntros: require('./images/tab/intros.png'),
  tabIntrosFilled: require('./images/tab/intros_filled.png'),
  tabContacts: require('./images/tab/contact.png'),
  tabContactsFilled: require('./images/tab/contact_filled.png'),
  tabProfile: require('./images/tab/profile.png'),
  tabProfileFilled: require('./images/tab/profile_filled.png'),
  tabCreateIntro: require('./images/tab/createIntro.png'),
  network: require('./images/splash/network.png'),
  rating: {
    great: require('./images/rating/rating-great.png'),
    ok: require('./images/rating/rating-ok.png'),
    notgood: require('./images/rating/rating-not-good.png')
  },
  arrow: {
    down: require('./images/arrow/arrow_down.png'),
    left: require('./images/arrow/arrow_left.png')
  },
  icons: {
    user: require('./images/icons/user.png'),
    checked: require('./images/icons/checked.png'),
    checked2: require('./images/icons/checked2.png'),
    error: require('./images/icons/error.png'),
    email: require('./images/icons/email.png'),
    lock: require('./images/icons/lock.png'),
    back_ios: require('./images/icons/arrow_back_ios.png'),
    back_android: require('./images/icons/arrow_back_android.png'),
    ios_search: require('./images/icons/ios_search.png'),
    ios_search_inside: require('./images/icons/ios_search_inside.png'),
    ios_clear: require('./images/icons/ios_clear.png'),
    android_search: require('./images/icons/android_search.png'),
    android_search_inside: require('./images/icons/android_search_inside.png'),
    close_android: require('./images/icons/close_android.png'),
    edit: require('./images/icons/edit.png'),
    linkedin: require('./images/icons/linkedin.png'),
    warning: require('./images/icons/warning-chicklet.png'),
    checkMark: require('./images/icons/check-mark.png'),
    linkedinGray: require('./images/icons/linkedin-gray.png'),
    caretDown: require('./images/icons/caret-down.png'),
    back2: require('./images/icons/arrow-back2.png'),
    forward: require('./images/icons/forward.png'),
    lockContent: require('./images/icons/lock_content.png'),
    settings: require('./images/icons/settings.png'),
    caretRight: require('./images/icons/caret-right.png'),
    trash: require('./images/icons/trashcan.png')
  },
  filter: {
    all: require('./images/filter/all.png'),
    active: require('./images/filter/active.png'),
    received: require('./images/filter/received.png'),
    archived: require('./images/filter/archived.png'),
    checkmark: require('./images/filter/check-mark.png'),
    declined: require('./images/filter/declined.png'),
    completed: require('./images/filter/completed.png'),
    noreply: require('./images/filter/noreply.png'),
    rated: require('./images/filter/rated.png'),
    confirm: require('./images/filter/confirm.png'),
    filter: require('./images/filter/filter.png'),
    recent: require('./images/filter/recent.png'),
    frequent: require('./images/filter/frequent.png')
  },
  homeCard: {
    requestForwardable: require('./images/home-card/request-forwardable.png'),
    noOptIn: require('./images/home-card/no-opt-in.png')
  },
  timeline: {
    automatic_logo: require('./images/timeline/automatic_logo.png'),
    rating_great: require('./images/timeline/rating-great.png'),
    rating_not_good: require('./images/timeline/rating-not-good.png'),
    rating_ok: require('./images/timeline/rating-ok.png')
  },
  contact: {
    linkedin: require('./images/contact/contact-linkedin.png'),
    twitter: require('./images/contact/contact-twitter.png'),
    intro_link: require('./images/contact/contact-intro-link.png'),
    make_intro: require('./images/contact/contact-make-intro.png'),
    arrow: require('./images/contact/contact-arrow.png'),
    someone: require('./images/contact/contact-someone.png'),
    copy: require('./images/contact/copy.png'),
    preview: require('./images/contact/preview.png'),
    share: require('./images/contact/share.png'),
    check_mark: require('./images/contact/check-mark.png')
  }
}
